export const LOGO = require('./amakenLogo.png') 
export const Camera = require('./camera.png') 
export const EventImage = require('./eventImage.png')
export const HeaderBG = require('./headerBG.jpg')
export const Hiking = require('./hiking.png')
export const TicketLine = require('./ticketLine.png')
export const AmakenLogo = require('./amakenLogo.png')
